export { default as Header } from './Header';
export { default as Navbar } from './Navbar';
export { default as BigSlide } from './BigSlide';
export { default as Rewards } from './Rewards';
export { default as MultipleSlide } from './MultipleSlide';
export { default as CommentsSlide } from './CommentsSlide';
export { default as Collapse } from './Collapse';
export { default as Footer } from './Footer';
export { default as ModalConfirm } from './ModalConfirm';
